In [2]:
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pickle
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from distutils.dir_util import copy_tree


In [3]:
pathTrain=r'c:\Users\VARSHA\Desktop\clg\ML\autism\train'
pathValid=r'c:\Users\VARSHA\Desktop\clg\ML\autism\valid'
pathTest=r'c:\Users\VARSHA\Desktop\clg\ML\autism\test'
categories=['autistic','non_autistic']
train =[]
valid =[]
test=[]

In [4]:
def prepareData(path):
    data =[]
    for category in categories:
        p=os.path.join(path, category)
        lable= categories.index(category) 
        for img in os.listdir(p):
            img_path = os.path.join(p,img)
            image= cv2.imread(img_path ,0)
            image= cv2.resize(image,(50,50))# size of image 50*50
            last_image = np.array(image).flatten()
            data.append([last_image,lable])
    print("size of data: in path: ",path," :::: ",len(data))
    return  data

In [5]:
train =prepareData(pathTrain)
valid =prepareData(pathValid)
test=prepareData(pathTest)

size of data: in path:  c:\Users\VARSHA\Desktop\clg\ML\autism\train  ::::  2536
size of data: in path:  c:\Users\VARSHA\Desktop\clg\ML\autism\valid  ::::  100
size of data: in path:  c:\Users\VARSHA\Desktop\clg\ML\autism\test  ::::  300


In [6]:
pick_in_train = open('train.pickle','wb')
pickle.dump(train,pick_in_train)
pick_in_train.close()

pick_in_valid = open('valid.pickle','wb')
pickle.dump(valid,pick_in_valid)
pick_in_valid.close()

pick_in_test = open('test.pickle','wb')
pickle.dump(test,pick_in_test)
pick_in_test.close()

In [7]:
len(train )

2536

In [8]:
pick_in_tr=open('train.pickle','rb')
data_tr=pickle.load(pick_in_tr)
pick_in_tr.close()

pick_in_v=open('valid.pickle','rb')
data_v=pickle.load(pick_in_v)
pick_in_v.close()

pick_in_te=open('test.pickle','rb')
data_te=pickle.load(pick_in_te)
pick_in_te.close()


random.shuffle(data_tr)
random.shuffle(data_v)
random.shuffle(data_te)


In [9]:
features_train =[]
lables_train=[]

features =[]
lables=[]

for f, l in data_tr:
    features.append(f)
    lables.append(l)
for f, l in data_v:
    features.append(f)
    lables.append(l)
for f, l in data_te:
    features.append(f)
    lables.append(l)

In [10]:
print(len(data_tr))
print(len(data_v))
print(len(data_te))

2536
100
300


In [11]:
len(lables)

2936

In [12]:
len(features)

2936

In [13]:
X,Y=features,lables

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [18]:
test_size = 0.2
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [41]:
model=RandomForestClassifier(n_estimators=120)
model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=120)

In [43]:
model.score(X_test,Y_test)

0.7295918367346939

In [44]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 120,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [49]:
model.predict(X_test[:10])

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

In [51]:
X_test

[array([240, 240, 240, ...,  68, 143, 190], dtype=uint8),
 array([175,  65,  42, ..., 164, 122,  76], dtype=uint8),
 array([110, 112,  91, ..., 251, 250, 255], dtype=uint8),
 array([ 76,  72,  93, ..., 219, 225, 240], dtype=uint8),
 array([79, 76, 86, ..., 11, 19, 26], dtype=uint8),
 array([166, 168, 170, ...,   8,   3,   4], dtype=uint8),
 array([ 76, 231, 168, ..., 214, 190, 242], dtype=uint8),
 array([113, 105, 111, ...,  74,  67,  65], dtype=uint8),
 array([254, 254, 255, ...,  63,  64,  60], dtype=uint8),
 array([100, 107, 111, ..., 250, 252, 252], dtype=uint8),
 array([168, 110,  77, ..., 117, 120, 118], dtype=uint8),
 array([154, 123, 211, ..., 230, 237, 109], dtype=uint8),
 array([ 77,  97,  81, ...,  71,  90, 110], dtype=uint8),
 array([243, 198, 149, ...,  71,  56,  57], dtype=uint8),
 array([161, 161, 161, ...,  76,  97,  98], dtype=uint8),
 array([59, 59, 59, ..., 90, 87, 78], dtype=uint8),
 array([ 68,  70,  71, ..., 150, 106, 110], dtype=uint8),
 array([175, 199, 204, ...